/**
 * Sidebar items for the private and per-org groups.
 *
 * Only these two groups need building. The public part of a private page's
 * sidebar is handed to `<StarlightPage>` in the same config shape
 * `astro.config.mjs` uses — the prop is typed `StarlightUserConfig['sidebar']`
 * and validated by Starlight's own `SidebarItemSchema`, so `slug` shorthand and
 * `autogenerate` work there untouched. Re-implementing that walk here would
 * duplicate ordering, nesting and index-page rules that are Starlight's to
 * define, and would drift from them on upgrade.
 *
 * Private and org docs are the exception, and the reason this file exists: they
 * live outside the `docs` collection (that is the security boundary — see
 * wiki/private-docs.md), so nothing Starlight autogenerates can reach them and
 * their links must be built explicitly.
 *
 * Everything here takes entries as arguments rather than importing
 * `astro:content`, so it runs under `node --test`.
 * `src/lib/private-sidebar.mjs` is the glue that feeds it real collections.
 *
 * ## Entry ids
 *
 * Astro's glob loader slugifies each path segment with github-slugger, joins
 * them with `/`, then applies `.replace(/\/index$/, '')`
 * (`astro/dist/content/utils.js:getContentEntryIdAndSlug`). The leading slash
 * in that regex is why a collection-root `index.mdx` keeps the id `index` while
 * a nested one collapses to its parent directory. Read back out of the data
 * store after a sync:
 *
 *     private-docs/index.mdx                 -> "index"
 *     private-docs/example-private-guide.mdx -> "example-private-guide"
 *     private-docs/guides/index.mdx          -> "guides"
 *     org-docs/acme/index.mdx                -> "acme"
 *     org-docs/acme/setup.mdx                -> "acme/setup"
 *     org-docs/acme/deep/index.mdx           -> "acme/deep"
 *
 * Two facts below are load-bearing: no id ever ends in `/index`, so nothing
 * needs to strip that suffix; and an org's landing page id *is* the org slug
 * exactly, so filtering on `id.startsWith(org + '/')` alone would miss the
 * landing page of every org.
 *
 * ## The org slug has to match a slugified directory name
 *
 * A group is matched by comparing the token's org slug against ids, and those
 * ids went through github-slugger, which lowercases and strips punctuation
 * (measured: `Acme Labs` and `acme-labs` both become `acme-labs`; `acme.co`
 * becomes `acmeco`). So an org folder must already be named the way its slug is
 * spelled in the SSO token, or the reader gets no group at all. Normalising the
 * slug here to paper over that would be worse than the empty group: it would
 * make two different directory names answer to one org.
 *
 * ## `hidden` removes the link, not the page
 *
 * `sidebar.hidden` is Starlight's own frontmatter field, documented as
 * preventing a page from appearing in autogenerated sidebar groups. It is a
 * navigation setting, so a hidden private page is still served to any logged-in
 * reader who knows its URL. Access is the middleware's decision, never this
 * file's.
 */

/**
 * Ordered entries first (by `sidebar.order`), then the rest alphabetically.
 *
 * `Infinity` stands in for "no order". Nothing real can tie with it: Starlight's
 * docsSchema types `order` as `z.number().optional()`, and zod rejects both
 * infinities (as well as NaN and strings) at build time, so an unordered entry
 * always sorts after every ordered one. When two entries do share an order, the
 * subtraction is `0` and the comparison falls through to the id — which is
 * unique per collection, making this a total order that does not lean on
 * `Array#sort` being stable. Comparing ids with `localeCompare` rather than
 * titles is what Starlight does for the public sidebar
 * (`utils/navigation.ts:sortDirEntries`), so both halves of a reader's nav sort
 * the same way.
 */
const byOrderThenId = (a, b) =>
	(a.data.sidebar?.order ?? Infinity) - (b.data.sidebar?.order ?? Infinity) ||
	a.id.localeCompare(b.id);

const labelOf = (entry) => entry.data.sidebar?.label ?? entry.data.title;

/**
 * Sorted `{ label, link }` items for a list of collection entries.
 *
 * Filters before sorting, so the caller's array is never reordered in place —
 * `src/lib/private-sidebar.mjs` walks every org over one shared
 * `getCollection('orgDocs')` result.
 */
export function entriesToItems(entries, linkFor) {
	return entries
		.filter((entry) => !entry.data.sidebar?.hidden)
		.sort(byOrderThenId)
		.map((entry) => ({ label: labelOf(entry), link: linkFor(entry) }));
}

/** Link for a `privateDocs` entry. `index` is the section landing page. */
export const privateLinkFor = (entry) =>
	entry.id === 'index' ? '/private/' : `/private/${entry.id}/`;

/**
 * Link builder for one org's `orgDocs` entries.
 *
 * The org's landing page has the org slug as its whole id; everything else is
 * prefixed with `<org>/`. Only valid for entries `orgGroup` has already matched
 * to `org` — the slice assumes that prefix is there.
 */
export const orgLinkFor = (org) => (entry) =>
	entry.id === org
		? `/private/orgs/${org}/`
		: `/private/orgs/${org}/${entry.id.slice(org.length + 1)}/`;

/**
 * Sidebar group for one org, or null if it has no content.
 *
 * Labelled by the org's landing page title, so the folder name `acme` can
 * display as "Acme docs" without a separate slug-to-name mapping.
 *
 * @param {string} org Org slug from the session, byte-verbatim as the SSO token
 *   spelled it — see `src/lib/auth/guards.mjs` for why it is never repaired.
 */
export function orgGroup(org, orgEntries) {
	// A slug containing a slash is refused rather than matched. It is the one
	// value that can cross a path boundary into another org's ids: `acme/deep`
	// is a real Acme page (`org-docs/acme/deep/index.mdx`), so a misconfigured
	// IdP claiming that org would put Acme's page title in a non-member's
	// sidebar. Following the link 404s — `classifyPath` captures a single
	// segment, `/private/orgs/([^/]+)`, so the middleware would ask for
	// membership of `acme`, not `acme/deep` — but the title has already leaked.
	// That same single-segment capture is why refusing costs nothing: no org
	// whose slug contains a slash can ever be granted, so none of its content
	// is reachable as that org anyway.
	if (org.includes('/')) return null;
	// `id === org` catches the landing page; the trailing slash on the prefix
	// keeps org `acme` from swallowing `acme-labs/`, which would put one
	// customer's pages in another customer's sidebar. Both comparisons are
	// literal string operations, never a RegExp, so a slug carrying regex
	// metacharacters matches only itself.
	const entries = orgEntries.filter(
		(entry) => entry.id === org || entry.id.startsWith(`${org}/`)
	);
	if (entries.length === 0) return null;
	const landing = entries.find((entry) => entry.id === org);
	return {
		label: landing ? landing.data.title : org,
		items: entriesToItems(entries, orgLinkFor(org)),
	};
}
